name: Trigger Remote SBOM Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  call-remote-workflow:
    permissions:
      contents: write # the shared workflow uploads the SBOM onto the release
    uses: eclipse-xfsc/dev-ops/.github/workflows/sbom-golang.yml@main
    secrets:
      GH_TOKEN: ${{ github.token }}
